# Generated by Django 4.2 on 2023-11-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Vista')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la habitación')),
                ('capacity', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('num_beds', models.CharField(verbose_name='Número de camas')),
                ('view', models.ManyToManyField(to='administracion.roomview', verbose_name='Vista')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='habitaciones/', verbose_name='Imagen de la habitacion')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_imgs', to='administracion.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Desde: ')),
                ('date_to', models.DateField(verbose_name='Hasta: ')),
                ('price', models.DecimalField(decimal_places=2, help_text='Usar punto (.) para los decimales y no usar separador de miles', max_digits=10, verbose_name='Valor por noche (AR$)')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='administracion.roomtype', verbose_name='Tipo de Habitación')),
                ('room_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.roomview', verbose_name='Vista de la Habitación')),
            ],
        ),
    ]
