# Generated by Django 4.2 on 2023-11-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Desde: ')),
                ('date_to', models.DateField(verbose_name='Hasta: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por noche (AR$)')),
            ],
        ),
    ]
