# Generated by Django 4.2 on 2023-11-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Usar punto (.) para los decimales y no usar separador de miles', max_digits=10, verbose_name='Valor por noche (AR$)'),
        ),
    ]
