# Generated by Django 4.2 on 2023-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=44, verbose_name='Titulo')),
                ('informacion', models.CharField(blank=True, max_length=144, verbose_name='Informacion')),
                ('imagen', models.URLField(default='https://placehold.co/600x400/webp', verbose_name='Imagen')),
            ],
        ),
    ]
