# Generated by Django 4.2 on 2023-10-12 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=44, verbose_name='Titulo')),
                ('informacion', models.CharField(blank=True, max_length=144, verbose_name='Informacion')),
                ('imagen', models.URLField(default='https://placehold.co/600x400/webp', verbose_name='Imagen')),
                ('lugar', models.CharField(blank=True, default='Preguntar', max_length=44, null=True, verbose_name='Lugar')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('Platos de Autor', 'Platos de Autor'), ('Opciones rapidas', 'Opciones rapidas'), ('Cocteles y tragos', 'Cocteles y tragos'), ('Whiskeys', 'Whiskeys'), ('Cofee', 'Cofee'), ('Non Cofee', 'Non Cofee'), ('Smoothie', 'Smoothie'), ('Bakery and pastry', 'Bakery and pastry')], max_length=100, verbose_name='categoria')),
                ('precio', models.IntegerField(max_length=100, verbose_name='precio')),
            ],
        ),
    ]
