# Generated by Django 4.2 on 2023-10-06 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(blank=True, default='Preguntar', max_length=44, null=True, verbose_name='Lugar'),
        ),
    ]
