# Generated by Django 4.2 on 2023-11-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_eventos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='informacion',
            field=models.CharField(blank=True, max_length=244, verbose_name='Informacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(blank=True, default='Preguntar', max_length=144, null=True, verbose_name='Lugar'),
        ),
    ]
