# Generated by Django 4.2 on 2023-10-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Comidas', 'Comidas'), ('Cafeteria', 'Cafeteria'), ('Bebidas', 'Bebidas')], max_length=100, verbose_name='categoria'),
        ),
    ]
